Display events
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #15
Opened 2024-01-25 02:08 UTC by angel23v

Display all the events once we click on "Iniciar" button

For more info see: https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/issues/11

2024-01-25 06:59 UTC, angel23v commented
I pushed new changes

2024-01-26 00:45 UTC, MauricioNC requested changes

2024-01-26 00:45 UTC, MauricioNC commented on app/views/events/index.html.erb
> +</html>
Add a new empty line after your code

2024-01-26 00:45 UTC, MauricioNC requested changes

2024-01-26 00:45 UTC, MauricioNC commented on app/views/events/_navbar.html.erb
> +</nav>
Same, add a new empty line after your code

2024-01-26 00:47 UTC, MauricioNC requested changes

2024-01-26 00:47 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +      redirect_to '/views/events/index'
You can use the prefixes that rails gives you with resources.

See  the documentation at:
https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default

2024-01-26 00:53 UTC, MauricioNC requested changes

2024-01-26 00:53 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +    params.require(:event).permit(:Titulo, :Descripcion, :Fecha, :Ubicacion, :Costo)
The fields in a table must be lowercase.
You can run a migration to rename this fields.

See the documentation at:
https://edgeguides.rubyonrails.org/active_record_migrations.html
https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column

2024-01-26 00:53 UTC, MauricioNC commented on app/controllers/events_controller.rb
> +    params.require(:event).permit(:Titulo, :Descripcion, :Fecha, :Ubicacion, :Costo)
The fields in a table must be lowercase
You can run a migration to rename this fields.

See the documentation at:
https://edgeguides.rubyonrails.org/active_record_migrations.html
https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column

2024-01-26 02:10 UTC, MauricioNC requested changes

2024-01-26 02:10 UTC, MauricioNC commented on app/views/events/main.html.erb
> +</html>
Add new empty line at the end of your code

2024-01-26 02:31 UTC, MauricioNC approved these changes

2024-01-27 00:11 UTC, juperameza approved these changes
LGTM

2024-01-27 00:30 UTC, merged