Add delete button for events
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #21
Opened 2024-01-31 01:44 UTC by Bryanroal

Added button of eliminate
Added metod and rute
For more infomation see issue #20

2024-01-31 02:11 UTC, juperameza requested changes

2024-01-31 02:11 UTC, juperameza commented on app/controllers/events_controller.rb
> +    @event =  Event.find(params[:id])
you're repeating this line multiple times move it to another function and add a before action. [Read this](https://dannemanne.com/posts/ruby_on_rails_explained_before_action)

2024-01-31 02:11 UTC, juperameza commented on config/routes.rb
> +  delete'/events/:id',  to: 'events#destroy'
This also looks good but. Youre doing mannually what resources do.
[Resources](https://guides.rubyonrails.org/routing.html#singular-resources)
[ANother reading](https://launchschool.com/books/demystifying_rails/read/routes_and_resources)

2024-01-31 02:18 UTC, MauricioNC requested changes

2024-01-31 02:18 UTC, MauricioNC commented on app/views/events/index.html.erb
> +              </svg>
You can put the svg file in a different file and just render it, by this way your code will looks more readable

2024-02-01 01:08 UTC, juperameza approved these changes
LGTM

2024-02-01 01:11 UTC, MauricioNC approved these changes

2024-02-01 01:11 UTC, merged