Filter view on events
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #25
Opened 2024-02-03 02:21 UTC by angel23v

When you create a public event, all the users will be able to see it but if you create a private event you just gonna see it

2024-02-03 03:22 UTC, juperameza requested changes

2024-02-03 03:22 UTC, juperameza commented on app/models/user.rb
> +  has_many :event
Lol my bad this should be events

2024-02-04 18:32 UTC, juperameza approved these changes
Lgtm

2024-02-06 17:01 UTC, juperameza approved these changes
Lgtm

2024-02-06 21:33 UTC, MauricioNC approved these changes

2024-02-06 21:47 UTC, merged