Create map to save & show ubication
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #28
Opened 2024-02-06 05:08 UTC by angel23v

## Quick Info
   - Map to save the ubication where you click
   - Search button tool
   - Show map with the ubication saved when you edit an event
   - Navigate inside the map with the cursor
   - FIll automatically ubication fields on the form  (ubicacion, latitud, longitud)

Migrations? 
Yes, added latitud & longitud columns

## What does this change?
The way to save & show the ubication

## Why are you changing that?
Because it looks better with a interactive map and makes a better experience for the user 

## How do you manually test this?
Clicking many times on the map to see if the infomation was showed on the ubication fields.
Saving events and see the correct ubication info on my view
Editing events to see if the ubicatiion saved was showed on the map

## Screenshots
![add_event](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/918900fe-797c-4245-92a3-2241c6a60239)
![show_and_edit_ubi](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/dbf1fa08-ba9b-43f0-8cff-0ae7f268d96d)

2024-02-06 21:40 UTC, MauricioNC requested changes

2024-02-06 21:40 UTC, MauricioNC commented on app/javascript/controllers/map_controller.js
> +    const apiKey = "pk.8ef046976867e15790d27dae0c26d553";
Don't leave this api key directly in the code, please move it to an environment variable instead

2024-02-06 21:40 UTC, MauricioNC commented on app/views/layouts/_navbar.html.erb
>          <li class="nav-item">
You can improve the logic of this code. Have you used the unless statement?

2024-02-06 21:40 UTC, MauricioNC commented on app/views/layouts/application.html.erb
> +
Remove blank spaces

2024-02-06 23:34 UTC, angel23v commented on app/views/layouts/_navbar.html.erb
>          <li class="nav-item">
Yes, It will be better if I use ternary operator?

2024-02-06 23:44 UTC, MauricioNC commented on app/views/layouts/_navbar.html.erb
>          <li class="nav-item">
No, ternary operator is recommended to use for short evaluations.

In the first if, you are evaluating a negative condition, you can use unless instead.
In the second if, you have the li tag outside of the if statement, if the condition is not met, you will have an empty li tag, you can move the li tag inside the if statement, by this way, if the condition is not met, the li tag will not be created.

2024-02-06 23:46 UTC, MauricioNC commented on app/views/layouts/_navbar.html.erb
>          <li class="nav-item">
or you can user an if else statement, but sometimes the linter marks a suggestion to replace the negative conditions for unless statement.

2024-02-07 00:14 UTC, angel23v commented on app/javascript/controllers/map_controller.js
> +    const apiKey = "pk.8ef046976867e15790d27dae0c26d553";
is there any documentation?

2024-02-07 00:19 UTC, angel23v commented on app/views/layouts/_navbar.html.erb
>          <li class="nav-item">
Thanks I already try with unless statement

2024-02-07 00:29 UTC, MauricioNC commented on app/javascript/controllers/map_controller.js
> +    const apiKey = "pk.8ef046976867e15790d27dae0c26d553";
Personally, I've never faced to this kind of situation. May be a solution could be save that api key into the credentials file and then create a method that returns the api key. 

To edit this file you can run `rails credentials:edit`.

And just call this method from Stimulus.

2024-02-07 06:27 UTC, angel23v commented on app/javascript/controllers/map_controller.js
> +    const apiKey = "pk.8ef046976867e15790d27dae0c26d553";
Thanks I try with that option & I wasn`t able to solve but searching I found a gem call "dotenv" and it works for me.

2024-02-07 17:54 UTC, MauricioNC approved these changes
LGTM!

2024-02-07 23:47 UTC, juperameza approved these changes
LGTM

2024-02-07 23:47 UTC, merged