Improve styles
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #31
Opened 2024-02-09 04:29 UTC by angel23v

## Quick Info
- Improving devise views
  - sign_in view
  - sign_up view
  - reset password view

## What does this change?
A better view for the user

## Why are you changing that?
Because it was too simple the default view

## How do you manually test this?
Reload the page/server and watch changes

## Screenshots (if apply)
![login](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/ca3591a1-6295-476c-98d4-11d97d938a46)
![passwrod](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/cea51f31-9513-4d78-b1c3-346ff478b9e4)
![register](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/7ae2103a-e68d-46dc-83cc-c50d7d747a79)

2024-02-09 23:06 UTC, MauricioNC approved these changes

2024-02-09 23:38 UTC, juperameza requested changes

2024-02-09 23:38 UTC, juperameza commented on app/assets/stylesheets/login.scss
> +}
ORder  styles alphabetically

2024-02-09 23:38 UTC, juperameza commented on app/views/devise/shared/_links.html.erb
> +  <br />
Dont use br

2024-02-09 23:38 UTC, juperameza commented on app/views/devise/shared/_links.html.erb
> +  <br />
Also this if is just empty delete it completely

2024-02-12 19:50 UTC, juperameza approved these changes

2024-02-12 19:55 UTC, merged