Add Option to Filter Events
BrightCoders-Institute/s5a1-administrador-de-eventos-team4 pull request #33
Opened 2024-02-12 20:46 UTC by angel23v

## Quick Info

Improve two options to filter user events (by date or type), this in my events but if you go to Public Events that other users had created you also have a filter option but just by date because all are publics
There is a button to reset the info

## What does this change?
User Experience to get an event faster improving filters

## Why are you changing that?
Because its a better way to get an event, more comfortable and get a better user experience

## How do you manually test this?
Searching events using my filters options.  In my events and also in public events

## Screenshots 
# FIlter Options
![filters](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/61b708fd-7022-438e-bab1-00ba5788dc5c)
# Result searched by public event
![result_Dos](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/a3965b9f-2bed-4a31-84e0-12dbf11c607d)
# Result searched by date
![result](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/6b5f5fd7-9601-4c57-b45e-5207143100d5)
# Public Events FIlter
![public_events_filter](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team4/assets/86389712/1230c980-6bbe-4bfb-9b4f-2d30df2d26a1)

2024-02-12 22:40 UTC, MauricioNC requested changes

2024-02-12 22:40 UTC, MauricioNC commented on app/views/layouts/_filter.html.erb
> +      <% end %>
You are evaluating same the conditions two times, you could do it in a single evaluation. You can improve the logic of this code too.

2024-02-12 22:40 UTC, MauricioNC commented on app/views/events/public.html.erb
> +            </img>
Same here.

2024-02-12 22:40 UTC, MauricioNC commented on app/views/events/index.html.erb
> +        </img>
May be you can change the logic of this code, since you are wrapping an image tag inside another image tag if the condition is met.

2024-02-12 22:40 UTC, MauricioNC commented on app/views/events/public.html.erb
> +                <%= link_to 'Eliminar Foto', destroy_foto_event_path(event), method: :delete, data: { confirm: '¿Estás seguro de que quieres eliminar esta foto?' } %>
Please use a single language, English or Spanish.

2024-02-12 22:44 UTC, MauricioNC commented on app/views/events/index.html.erb
> +        </img>
Sorry, this requested change should be the first cx

2024-02-12 22:44 UTC, MauricioNC commented on app/views/events/public.html.erb
> +            </img>
And this the second cx

2024-02-13 00:27 UTC, MauricioNC approved these changes

2024-02-14 00:01 UTC, juperameza approved these changes

2024-02-14 00:03 UTC, merged